[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "TSP_Ant"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12"
pip = "*"
setuptools = "*"
numpy = "*"
numba = "*"
streamlit = "1.40.*"
matplotlib = "*"
